<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>"
      lang="<?php echo $this->getLang() ?>">
    <head>
        <?php echo $this->getChildHtml('head') ?>
    </head>
    <body<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : '' ?>>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-5CFLTF"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5CFLTF');</script>
<!-- End Google Tag Manager -->
        <?php echo $this->getChildHtml('after_body_start') ?>
        <div class="wrapper">
            <?php echo $this->getChildHtml('global_notices') ?>
            <?php echo $this->getChildHtml('global_notices') ?>
            <div class="page">
                <?php echo $this->getChildHtml('page_start') ?>
                <?php echo $this->getChildHtml('header') ?>
                <div class="main-container col3-layout">
                    <div class="main">
                        <?php echo $this->getChildHtml('breadcrumbs') ?>
                        <div class="col-wrapper">
                            <div class="col-main">
                                <div class="col-inner" id="col-inner">
                                    <?php echo $this->getChildHtml('global_messages') ?>
                                    <?php echo $this->getChildHtml('content') ?>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>
                        </div>
                        <div class="col-right sidebar"><?php echo $this->getChildHtml('right') ?></div>
                    </div>
                </div>
                <?php echo $this->getChildHtml('footer') ?>
                <?php echo $this->getChildHtml('before_body_end') ?>
            </div>
        </div>
        <?php echo $this->getAbsoluteFooter() ?>
    </body>
</html>
